/robot1/controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/robot1/velocity_controller:
  ros__parameters:
    joints:
      - robot1_RightMotor
      - robot1_LeftMotor
    command_interfaces: 
      - velocity
    state_interfaces: 
      - position
      - velocity

/robot1/joint_state_broadcaster:
  ros__parameters:
    joints: 
      - robot1_RightMotor
      - robot1_LeftMotor
      - robot1_CasterJoint
    interfaces: 
      - position 
      - velocity

