/robot2/controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/robot2/velocity_controller:
  ros__parameters:
    joints:
      - robot2_RightMotor
      - robot2_LeftMotor
    command_interfaces: 
      - velocity
    state_interfaces: 
      - position
      - velocity

/robot2/joint_state_broadcaster:
  ros__parameters:
    joints: 
      - robot2_RightMotor
      - robot2_LeftMotor
      - robot2_CasterJoint
    interfaces: 
      - position 
      - velocity
